import type { Metadata } from 'next';
import '@/globals.css';
import { MswComponent } from '@/mocks/msw.component';
import QueryProviders from '@/utils/queryProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body className="font-pretendard antialiased">
        <MswComponent />
        <QueryProviders>{children}</QueryProviders>
      </body>
    </html>
  );
};

export default RootLayout;
